In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\\Users\\admin\\Downloads\\ML_JupitorNotebook\\2020.csv")s

In [3]:
df

     year   make             model body_styles
0    2020  Acura               ILX   ["Sedan"]
1    2020  Acura               MDX     ["SUV"]
2    2020  Acura  MDX Sport Hybrid     ["SUV"]
3    2020  Acura               NSX   ["Coupe"]
4    2020  Acura               RDX     ["SUV"]
..    ...    ...               ...         ...
370  2020  Volvo               V60   ["Wagon"]
371  2020  Volvo               V90   ["Wagon"]
372  2020  Volvo              XC40     ["SUV"]
373  2020  Volvo              XC60     ["SUV"]
374  2020  Volvo              XC90     ["SUV"]

[375 rows x 4 columns]

In [10]:
df.shape

(375, 4)

In [5]:
df.shape

(375, 4)

In [6]:
df.head(10)

   year        make             model      body_styles
0  2020       Acura               ILX        ["Sedan"]
1  2020       Acura               MDX          ["SUV"]
2  2020       Acura  MDX Sport Hybrid          ["SUV"]
3  2020       Acura               NSX        ["Coupe"]
4  2020       Acura               RDX          ["SUV"]
5  2020       Acura               RLX        ["Sedan"]
6  2020       Acura  RLX Sport Hybrid        ["Sedan"]
7  2020       Acura               TLX        ["Sedan"]
8  2020  Alfa Romeo         4C Spider  ["Convertible"]
9  2020  Alfa Romeo            Giulia        ["Sedan"]

In [7]:
df.head(-20)

     year    make              model      body_styles
0    2020   Acura                ILX        ["Sedan"]
1    2020   Acura                MDX          ["SUV"]
2    2020   Acura   MDX Sport Hybrid          ["SUV"]
3    2020   Acura                NSX        ["Coupe"]
4    2020   Acura                RDX          ["SUV"]
..    ...     ...                ...              ...
350  2020  Toyota        RAV4 Hybrid          ["SUV"]
351  2020  Toyota            Sequoia          ["SUV"]
352  2020  Toyota             Sienna  ["Van/Minivan"]
353  2020  Toyota  Tacoma Access Cab       ["Pickup"]
354  2020  Toyota  Tacoma Double Cab       ["Pickup"]

[355 rows x 4 columns]

In [11]:
df[1:10]

   year        make             model      body_styles
1  2020       Acura               MDX          ["SUV"]
2  2020       Acura  MDX Sport Hybrid          ["SUV"]
3  2020       Acura               NSX        ["Coupe"]
4  2020       Acura               RDX          ["SUV"]
5  2020       Acura               RLX        ["Sedan"]
6  2020       Acura  RLX Sport Hybrid        ["Sedan"]
7  2020       Acura               TLX        ["Sedan"]
8  2020  Alfa Romeo         4C Spider  ["Convertible"]
9  2020  Alfa Romeo            Giulia        ["Sedan"]

In [9]:
df[1:10]

   year        make             model      body_styles
1  2020       Acura               MDX          ["SUV"]
2  2020       Acura  MDX Sport Hybrid          ["SUV"]
3  2020       Acura               NSX        ["Coupe"]
4  2020       Acura               RDX          ["SUV"]
5  2020       Acura               RLX        ["Sedan"]
6  2020       Acura  RLX Sport Hybrid        ["Sedan"]
7  2020       Acura               TLX        ["Sedan"]
8  2020  Alfa Romeo         4C Spider  ["Convertible"]
9  2020  Alfa Romeo            Giulia        ["Sedan"]