In [2]:
import pandas as pd
from apyori import apriori

In [3]:
df=pd.read_csv("Grocery_Dataset.csv")
df

     corned_b   peppers  bourbon  cracker   chicken    apples      coke
0      olives   bourbon     coke   turkey  ice_crea       ham  baguette
1      hering  corned_b   olives      ham    turkey   bourbon   peppers
2    baguette  sardines   apples  peppers   avocado  ice_crea   bourbon
3    baguette      soda   hering  cracker  heineken   peppers    apples
4    baguette      soda   hering  cracker  heineken  corned_b       ham
..        ...       ...      ...      ...       ...       ...       ...
995      soda    olives  bourbon  cracker  heineken   avocado   avocado
996  baguette  sardines   apples  peppers   avocado  ice_crea    olives
997  sardines  heineken  chicken     coke  ice_crea  corned_b   peppers
998    hering  corned_b   apples   olives     steak  baguette   peppers
999    olives   bourbon     coke   turkey  ice_crea   peppers   peppers

[1000 rows x 7 columns]

In [4]:
records=[]
for i in range(0,1000):
        records.append([str(df.values[i,j]) for j in range(0,7)])

In [11]:
association_rules=apriori(records,min_support=0.20,min_confidence=0.4,min_lift=1.8,min_length=2)

In [12]:
association_results=list(association_rules)

In [13]:
association_results

[RelationRecord(items=frozenset({'artichok', 'avocado'}), support=0.211, ordered_statistics=[OrderedStatistic(items_base=frozenset({'artichok'}), items_add=frozenset({'avocado'}), confidence=0.6918032786885245, lift=1.9057941561667344), OrderedStatistic(items_base=frozenset({'avocado'}), items_add=frozenset({'artichok'}), confidence=0.581267217630854, lift=1.9057941561667344)]),
 RelationRecord(items=frozenset({'coke', 'ice_crea'}), support=0.22, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coke'}), items_add=frozenset({'ice_crea'}), confidence=0.7457627118644068, lift=2.3826284724102456), OrderedStatistic(items_base=frozenset({'ice_crea'}), items_add=frozenset({'coke'}), confidence=0.7028753993610224, lift=2.3826284724102456)]),
 RelationRecord(items=frozenset({'hering', 'heineken', 'baguette'}), support=0.214, ordered_statistics=[OrderedStatistic(items_base=frozenset({'baguette'}), items_add=frozenset({'hering', 'heineken'}), confidence=0.5459183673469388, lift=1.8955498866213154), OrderedStatistic(items_base=frozenset({'hering', 'heineken'}), items_add=frozenset({'baguette'}), confidence=0.7430555555555556, lift=1.8955498866213152)]),
 RelationRecord(items=frozenset({'hering', 'corned_b', 'olives'}), support=0.202, ordered_statistics=[OrderedStatistic(items_base=frozenset({'corned_b'}), items_add=frozenset({'hering', 'olives'}), confidence=0.517948717948718, lift=2.0232371794871797), OrderedStatistic(items_base=frozenset({'hering', 'olives'}), items_add=frozenset({'corned_b'}), confidence=0.7890625, lift=2.0232371794871793)]),
 RelationRecord(items=frozenset({'cracker', 'soda', 'heineken'}), support=0.234, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cracker'}), items_add=frozenset({'soda', 'heineken'}), confidence=0.4804928131416838, lift=1.8696218410182248), OrderedStatistic(items_base=frozenset({'soda'}), items_add=frozenset({'cracker', 'heineken'}), confidence=0.7358490566037736, lift=2.0105165480977423), OrderedStatistic(items_base=frozenset({'cracker', 'heineken'}), items_add=frozenset({'soda'}), confidence=0.639344262295082, lift=2.0105165480977423), OrderedStatistic(items_base=frozenset({'soda', 'heineken'}), items_add=frozenset({'cracker'}), confidence=0.9105058365758755, lift=1.8696218410182248)])]

In [14]:
df_results=pd.DataFrame(association_results)
df_results

,items,support,ordered_statistics
0,"(artichok, avocado)",0.211,"[((artichok), (avocado), 0.6918032786885245, 1..."
1,"(coke, ice_crea)",0.220,"[((coke), (ice_crea), 0.7457627118644068, 2.38..."
2,"(hering, heineken, baguette)",0.214,"[((baguette), (hering, heineken), 0.5459183673..."
3,"(hering, corned_b, olives)",0.202,"[((corned_b), (hering, olives), 0.517948717948..."
4,"(cracker, soda, heineken)",0.234,"[((cracker), (soda, heineken), 0.4804928131416..."